import { Routes } from '@angular/router';
import { RoutesApp } from '../../shared/const/routes';
import { superAdminGuard } from '../../core/guards/super-admin.guard';
export default <Routes>[
  { path: RoutesApp.users, canActivate: [superAdminGuard], loadComponent: () => import('./users/users.component') },
  { path: `${RoutesApp.users}/new`, canActivate: [superAdminGuard], loadComponent: () => import('./users/user-form.component') },
  { path: `${RoutesApp.users}/:id/edit`, canActivate: [superAdminGuard], loadComponent: () => import('./users/user-form.component') },
  { path: RoutesApp.sellers, loadComponent: () => import('./sellers/sellers.component') },
  { path: `${RoutesApp.sellers}/:id`, loadComponent: () => import('./sellers/seller-review.component') },
  { path: RoutesApp.pickupPoints, canActivate: [superAdminGuard], loadComponent: () => import('./pickup-points/pickup-points.component') },
  { path: `${RoutesApp.pickupPoints}/new`, canActivate: [superAdminGuard], loadComponent: () => import('./pickup-points/pickup-point-form.component') },
  { path: `${RoutesApp.pickupPoints}/:id/edit`, canActivate: [superAdminGuard], loadComponent: () => import('./pickup-points/pickup-point-form.component') },
  { path: RoutesApp.shippingRates, loadComponent: () => import('./shipping-rates/shipping-rates.component') },
  { path: `${RoutesApp.shippingRates}/new`, loadComponent: () => import('./shipping-rates/shipping-rate-form.component') },
  { path: `${RoutesApp.shippingRates}/:id/edit`, loadComponent: () => import('./shipping-rates/shipping-rate-form.component') },
  { path: RoutesApp.breeds, canActivate: [superAdminGuard], loadComponent: () => import('./breeds/breeds.component') },
  { path: `${RoutesApp.breeds}/new`, canActivate: [superAdminGuard], loadComponent: () => import('./breeds/breed-form.component') },
  { path: `${RoutesApp.breeds}/:id/edit`, canActivate: [superAdminGuard], loadComponent: () => import('./breeds/breed-form.component') },
  { path: RoutesApp.onboardingSurvey, canActivate: [superAdminGuard], loadComponent: () => import('./onboarding-survey/onboarding-survey.component') },
  { path: `${RoutesApp.onboardingSurvey}/new`, canActivate: [superAdminGuard], loadComponent: () => import('./onboarding-survey/survey-question-form.component') },
  { path: `${RoutesApp.onboardingSurvey}/:id/edit`, canActivate: [superAdminGuard], loadComponent: () => import('./onboarding-survey/survey-question-form.component') },
  { path: RoutesApp.sellerSegments, canActivate: [superAdminGuard], loadComponent: () => import('./seller-segments/seller-segments.component') },
  { path: `${RoutesApp.sellerSegments}/new`, canActivate: [superAdminGuard], loadComponent: () => import('./seller-segments/seller-segment-form.component') },
  { path: `${RoutesApp.sellerSegments}/:id/edit`, canActivate: [superAdminGuard], loadComponent: () => import('./seller-segments/seller-segment-form.component') },
  { path: `${RoutesApp.sellerSegments}/:id/sellers`, canActivate: [superAdminGuard], loadComponent: () => import('./seller-segments/seller-segment-sellers.component') },
  { path: RoutesApp.commissionRules, canActivate: [superAdminGuard], loadComponent: () => import('./commission-rules/commission-rules.component') },
  { path: `${RoutesApp.commissionRules}/:segmentId/new`, canActivate: [superAdminGuard], loadComponent: () => import('./commission-rules/commission-rule-form.component') },
  { path: RoutesApp.commissionReview, canActivate: [superAdminGuard], loadComponent: () => import('./commission-review/commission-review.component') },
  { path: RoutesApp.settlements, canActivate: [superAdminGuard], loadComponent: () => import('./settlements/settlements.component') },
  { path: `${RoutesApp.settlements}/new`, canActivate: [superAdminGuard], loadComponent: () => import('./settlements/settlement-form.component') },
  { path: `${RoutesApp.settlements}/:id`, canActivate: [superAdminGuard], loadComponent: () => import('./settlements/settlement-detail.component') },
  { path: 'products', canActivate: [superAdminGuard], loadComponent: () => import('./products/products.component') },
  { path: 'products/bull/:bullId', canActivate: [superAdminGuard], loadComponent: () => import('./products/product-review.component') },
  { path: 'products/:id', canActivate: [superAdminGuard], loadComponent: () => import('./products/product-review.component') },
  { path: 'inventory', loadComponent: () => import('./inventory/inventory-overview.component') },
  { path: RoutesApp.settings, loadComponent: () => import('./settings/marketplace-settings.component') },
  { path: RoutesApp.dashboard, loadComponent: () => import('./dashboard/dashboard.component') },
  { path: '', redirectTo: RoutesApp.dashboard, pathMatch: 'full' },
];
