export enum RoutesApp {
    verifyEmail = 'verify-email',
    dashboard = 'dashboard',
    callback = 'callback',
    sellers = 'sellers',
    signIn = 'sign-in',
    signUp = 'sign-up',
    admin = 'admin',
    users = "users",
    catalog = 'catalog',
    cart = 'cart',
    checkout = 'checkout',
    pickupPoints = 'pickup-points',
    shippingRates = 'shipping-rates',
    breeds = 'breeds',
    root = '',
}